import puppeteer from "puppeteer-core";
import type { Language } from "@shared/schema";

const titles: Record<string, string> = {
  English: "7-Day Treatment Plan",
  Telugu: "7-రోజుల చికిత్స ప్రణాళిక",
  Hindi: "7-दिन की उपचार योजना",
};

function markdownToHtml(md: string): string {
  return md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^## (.*$)/gm, "<h2>$1</h2>")
    .replace(/^### (.*$)/gm, "<h3>$1</h3>")
    .replace(/^# (.*$)/gm, "<h1>$1</h1>")
    .replace(/^- (.*$)/gm, "<li>$1</li>")
    .replace(/^\d+\.\s+(.*$)/gm, '<li class="numbered">$1</li>')
    .split("\n")
    .reduce((acc: string[], line: string) => {
      if (line.startsWith("<li")) {
        if (acc.length === 0 || !acc[acc.length - 1].startsWith("<li")) {
          acc.push("<ul>");
        }
        acc.push(line);
      } else {
        if (
          acc.length > 0 &&
          (acc[acc.length - 1].startsWith("<li") ||
            acc[acc.length - 1] === "</li>")
        ) {
          acc.push("</ul>");
        }
        if (line.trim() && !line.startsWith("<h")) {
          acc.push(`<p>${line}</p>`);
        } else {
          acc.push(line);
        }
      }
      return acc;
    }, [])
    .join("\n");
}

function buildHtml(plan: string, language: string): string {
  const title = titles[language] || titles.English;
  const contentHtml = markdownToHtml(plan);
  const today = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title} - KhetSathi</title>
<style>
  @page {
    margin: 18mm 15mm 18mm 15mm;
    size: A4;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Noto Sans', 'Noto Sans Devanagari', 'Noto Sans Telugu', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #1a1a1a;
    font-size: 11pt;
    line-height: 1.6;
    background: #fff;
  }
  .header {
    text-align: center;
    padding-bottom: 12px;
    margin-bottom: 16px;
    border-bottom: 3px solid #16a34a;
  }
  .header .brand { font-size: 22pt; font-weight: 700; color: #16a34a; letter-spacing: 1px; }
  .header .subtitle { font-size: 10pt; color: #666; margin-top: 2px; }
  .header .plan-title { font-size: 16pt; font-weight: 600; color: #1a1a1a; margin-top: 8px; }
  .header .date { font-size: 9pt; color: #888; margin-top: 4px; }
  h1 { font-size: 15pt; font-weight: 700; color: #16a34a; margin-top: 18px; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 2px solid #e5e7eb; }
  h2 { font-size: 13pt; font-weight: 600; color: #15803d; margin-top: 18px; margin-bottom: 6px; padding-bottom: 4px; border-bottom: 1.5px solid #dcfce7; page-break-after: avoid; }
  h3 { font-size: 11pt; font-weight: 600; color: #374151; margin-top: 12px; margin-bottom: 4px; }
  p { margin: 4px 0; color: #374151; }
  ul { list-style: none; margin: 4px 0 8px 0; padding: 0; }
  li { position: relative; padding: 3px 0 3px 18px; color: #374151; line-height: 1.5; }
  li::before { content: ''; position: absolute; left: 4px; top: 10px; width: 6px; height: 6px; border-radius: 50%; background: #16a34a; }
  li.numbered::before { display: none; }
  strong { color: #1a1a1a; font-weight: 600; }
  em { font-style: italic; }
  .footer { margin-top: 24px; padding-top: 10px; border-top: 2px solid #e5e7eb; text-align: center; font-size: 8.5pt; color: #9ca3af; }
</style>
</head>
<body>
<div class="header">
  <div class="brand">KhetSathi</div>
  <div class="subtitle">AI Crop Doctor</div>
  <div class="plan-title">${title}</div>
  <div class="date">${today}</div>
</div>
<div class="content">
  ${contentHtml}
</div>
<div class="footer">
  Generated by KhetSathi - AI Crop Doctor &bull; For agricultural guidance only &bull; ${today}
</div>
</body>
</html>`;
}

export async function generatePdf(
  plan: string,
  language: string
): Promise<Buffer> {
  const html = buildHtml(plan, language);

  const browser = await puppeteer.launch({
    executablePath:
      process.env.CHROMIUM_PATH ||
      "/nix/store/zi4f80l169xlmivz8vja8wlphq74qqk0-chromium-125.0.6422.141/bin/chromium",
    headless: true,
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
    ],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "18mm", bottom: "18mm", left: "15mm", right: "15mm" },
    });
    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}
