import type { Language } from "@shared/schema";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, Download } from "lucide-react";

interface TreatmentPlanProps {
  plan: string;
  language: Language;
}

const titles: Record<Language, string> = {
  English: "7-Day Treatment Plan",
  Telugu: "7-రోజుల చికిత్స ప్రణాళిక",
  Hindi: "7-दिन की उपचार योजना",
};

const downloadLabels: Record<Language, string> = {
  English: "Download PDF",
  Telugu: "PDF డౌన్‌లోడ్",
  Hindi: "PDF डाउनलोड करें",
};

function markdownToHtml(md: string): string {
  return md
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/^- (.*$)/gm, '<li>$1</li>')
    .replace(/^\d+\.\s+(.*$)/gm, '<li class="numbered">$1</li>')
    .split("\n")
    .reduce((acc: string[], line: string) => {
      if (line.startsWith("<li")) {
        if (acc.length === 0 || !acc[acc.length - 1].startsWith("<li")) {
          acc.push("<ul>");
        }
        acc.push(line);
      } else {
        if (acc.length > 0 && acc[acc.length - 1].startsWith("<li") || (acc.length > 1 && acc[acc.length - 1] === "</li>" )) {
          acc.push("</ul>");
        }
        if (line.trim() && !line.startsWith("<h")) {
          acc.push(`<p>${line}</p>`);
        } else {
          acc.push(line);
        }
      }
      return acc;
    }, [])
    .join("\n");
}

function downloadAsPdf(plan: string, language: Language) {
  const title = titles[language];
  const contentHtml = markdownToHtml(plan);
  const today = new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const htmlDoc = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title} - KhetSathi</title>
<style>
  @page {
    margin: 18mm 15mm 18mm 15mm;
    size: A4;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    color: #1a1a1a;
    font-size: 11pt;
    line-height: 1.6;
    background: #fff;
  }
  .header {
    text-align: center;
    padding-bottom: 12px;
    margin-bottom: 16px;
    border-bottom: 3px solid #16a34a;
  }
  .header .brand {
    font-size: 22pt;
    font-weight: 700;
    color: #16a34a;
    letter-spacing: 1px;
  }
  .header .subtitle {
    font-size: 10pt;
    color: #666;
    margin-top: 2px;
  }
  .header .plan-title {
    font-size: 16pt;
    font-weight: 600;
    color: #1a1a1a;
    margin-top: 8px;
  }
  .header .date {
    font-size: 9pt;
    color: #888;
    margin-top: 4px;
  }
  h1 {
    font-size: 15pt;
    font-weight: 700;
    color: #16a34a;
    margin-top: 18px;
    margin-bottom: 8px;
    padding-bottom: 4px;
    border-bottom: 2px solid #e5e7eb;
  }
  h2 {
    font-size: 13pt;
    font-weight: 600;
    color: #15803d;
    margin-top: 18px;
    margin-bottom: 6px;
    padding-bottom: 4px;
    border-bottom: 1.5px solid #dcfce7;
    page-break-after: avoid;
  }
  h3 {
    font-size: 11pt;
    font-weight: 600;
    color: #374151;
    margin-top: 12px;
    margin-bottom: 4px;
  }
  p {
    margin: 4px 0;
    color: #374151;
  }
  ul {
    list-style: none;
    margin: 4px 0 8px 0;
    padding: 0;
  }
  li {
    position: relative;
    padding: 3px 0 3px 18px;
    color: #374151;
    line-height: 1.5;
  }
  li::before {
    content: '';
    position: absolute;
    left: 4px;
    top: 10px;
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: #16a34a;
  }
  li.numbered::before {
    display: none;
  }
  strong {
    color: #1a1a1a;
    font-weight: 600;
  }
  em { font-style: italic; }
  .footer {
    margin-top: 24px;
    padding-top: 10px;
    border-top: 2px solid #e5e7eb;
    text-align: center;
    font-size: 8.5pt;
    color: #9ca3af;
  }
  .safety-box {
    background: #fef3c7;
    border: 1px solid #f59e0b;
    border-radius: 6px;
    padding: 10px 14px;
    margin: 10px 0;
  }
  @media print {
    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  }
</style>
</head>
<body>
<div class="header">
  <div class="brand">KhetSathi</div>
  <div class="subtitle">AI Crop Doctor</div>
  <div class="plan-title">${title}</div>
  <div class="date">${today}</div>
</div>
<div class="content">
  ${contentHtml}
</div>
<div class="footer">
  Generated by KhetSathi - AI Crop Doctor &bull; For agricultural guidance only &bull; ${today}
</div>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(htmlDoc);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 400);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getSectionIcon(heading: string): string {
  const lower = heading.toLowerCase();
  const map: Record<string, boolean> = {
    diagnosis: lower.includes("diagnosis"),
    immediate: lower.includes("immediate"),
    prescription: lower.includes("prescription"),
    calendar: lower.includes("calendar") || lower.includes("action"),
    budget: lower.includes("budget"),
    safety: lower.includes("safety"),
    prevention: lower.includes("prevention") || lower.includes("future"),
  };
  for (const [, matched] of Object.entries(map)) {
    if (matched) return "matched";
  }
  return "default";
}

function formatPlan(plan: string): string {
  const escaped = escapeHtml(plan);

  let html = escaped
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^### (.*$)/gm, (_m, p1) => {
      return `<h3 class="text-sm font-semibold mt-3 mb-1.5 text-foreground/90">${p1}</h3>`;
    })
    .replace(/^## (.*$)/gm, (_m, p1) => {
      getSectionIcon(p1);
      return `<div class="section-header flex items-center gap-2 mt-5 mb-2 pb-1.5 border-b border-border"><h2 class="text-base font-semibold text-foreground">${p1}</h2></div>`;
    })
    .replace(/^# (.*$)/gm, '<h1 class="text-lg font-bold mt-5 mb-3 text-foreground">$1</h1>')
    .replace(/^- (.*$)/gm, '<li class="ml-4 pl-1 py-0.5 text-foreground/85 text-sm leading-relaxed">$1</li>')
    .replace(/^\d+\.\s+(.*$)/gm, '<li class="ml-4 pl-1 py-0.5 list-decimal text-foreground/85 text-sm leading-relaxed">$1</li>');

  const lines = html.split("\n");
  const processed: string[] = [];
  let inList = false;

  for (const line of lines) {
    if (line.startsWith("<li")) {
      if (!inList) {
        processed.push("<ul class='space-y-0.5 my-1.5'>");
        inList = true;
      }
      processed.push(line);
    } else {
      if (inList) {
        processed.push("</ul>");
        inList = false;
      }
      if (line.trim() && !line.startsWith("<h") && !line.startsWith("<div")) {
        processed.push(`<p class="my-1 text-sm text-foreground/85 leading-relaxed">${line}</p>`);
      } else {
        processed.push(line);
      }
    }
  }
  if (inList) processed.push("</ul>");

  return processed.join("\n");
}

export function TreatmentPlan({ plan, language }: TreatmentPlanProps) {
  return (
    <Card className="p-4 sm:p-5 border-primary/20 max-h-[60vh] overflow-y-auto" data-testid="card-treatment-plan">
      <div className="flex items-center justify-between gap-2 mb-3 pb-2 border-b border-border">
        <div className="flex items-center gap-2">
          <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary/10 flex-shrink-0">
            <Calendar className="w-4 h-4 text-primary" />
          </div>
          <h2 className="text-lg font-semibold" data-testid="text-plan-title">
            {titles[language]}
          </h2>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => downloadAsPdf(plan, language)}
          data-testid="button-download-plan"
        >
          <Download className="w-4 h-4 mr-1.5" />
          {downloadLabels[language]}
        </Button>
      </div>

      <div
        className="treatment-plan-content prose prose-sm max-w-none dark:prose-invert prose-headings:text-foreground prose-p:text-foreground/85 prose-li:text-foreground/85 prose-strong:text-foreground"
        data-testid="text-plan-content"
        dangerouslySetInnerHTML={{ __html: formatPlan(plan) }}
      />
    </Card>
  );
}
